FROM bitnami/spark:3.4.1
WORKDIR /opt/bitnami/spark

COPY ./spark-apps /opt/spark-apps
COPY ./spark-config/spark-defaults.conf /opt/bitnami/spark/conf/spark-defaults.conf
COPY ./spark-config/hive-site.xml /opt/bitnami/spark/conf/hive-site.xml