
name: Pyspark LakeHouse Lib Build 
on: workflow_dispatch
jobs:
  whl-builder:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    # - name: Set up Python 3.8
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.8
    - name: Copy Modules to Spark Cluster 
      run: |
        docker cp ./spark/. airflow-spark-spark-1:/opt/bitnami/spark/python
        docker cp ./spark/. airflow-spark-spark-worker-1:/opt/bitnami/spark/python
        docker cp ./spark/. airflow-spark-spark-worker-2:/opt/bitnami/spark/python
        docker cp ./spark/. airflow-spark-spark-worker-3:/opt/bitnami/spark/python