name: Pyspark Data Pipeline Configuration Deploy 
on: workflow_dispatch
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1

      - name: Minio Deploy
        uses: lovellfelix/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'wba'
          source_dir: $GITHUB_WORKSPACE/config
          target_dir: '/'