name: Pyspark Data Pipeline Configuration Deploy 
on: workflow_dispatch
jobs:
  deploy-datapipeline-config:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - name: deploy to minio
        run: mc cp --recursive $GITHUB_WORKSPACE/config minio/wba
